### ISSUE TITLE
get error with example

### ISSUE THREAD

**Issue by ralyodio** [jpowers/node-google-places#9]
``````
$ ./google 
search:  []

/Users/user/projects/weed.uy/google:11
  places.details({reference: response.results[0].reference}, function(err, res
                                                ^
TypeError: Cannot read property 'reference' of undefined
    at /Users/user/projects/weed.uy/google:11:49
    at IncomingMessage.<anonymous> (/Users/user/projects/weed.uy/node_modules/google-places/lib/google-places.js:82:11)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)```
``````

**Comment by ralyodio** [comment]
I had to enable the "Google Places" api.
